replicaCount: 2

image:
  repository: ciavash/testpod
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# OpenTelemetry
otel:
  enabled: true
  endpoint: "http://otel-collector.default.svc.cluster.local:4317"

# Canary deploymnet
traffic:
  stableLabel: stable
  canaryLabel: canary
  canaryWeight: 0
  mirror: false

# Istio
istio:
  enabled: false
  sidecarInject: true
  mTLS: true
  rateLimit:
    enabled: true
    requestsPerMinute: 200

# Probes
probes:
  readiness:
    enabled: true
    path: /info
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    enabled: true
    path: /info
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}

