apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-vs
spec:
  hosts:
    - "{{ include "myapp.fullname" . }}"
  http:
    - route:
        - destination:
            host: {{ include "myapp.fullname" . }}
            subset: {{ .Values.traffic.stableLabel }}
          weight: {{ sub 100 .Values.traffic.canaryWeight }}
        - destination:
            host: {{ include "myapp.fullname" . }}
            subset: {{ .Values.traffic.canaryLabel }}
          weight: {{ .Values.traffic.canaryWeight }}
      {{- if .Values.traffic.mirror }}      
      mirror:
        host: {{ include "myapp.fullname" . }}
        subset: {{ .Values.traffic.canaryLabel }}
      mirrorPercent: 100

