{{- if .Values.istio.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-vs
spec:
  hosts:
    - "{{ include "app.fullname" . }}"
  http:
    - route:
        - destination:
            host: {{ include "app.fullname" . }}
            subset: {{ .Values.traffic.stableLabel }}
          weight: {{ sub 100 .Values.traffic.canaryWeight }}
        - destination:
            host: {{ include "app.fullname" . }}
            subset: {{ .Values.traffic.canaryLabel }}
          weight: {{ .Values.traffic.canaryWeight }}
      {{- if .Values.traffic.mirror }}      
      mirror:
        host: {{ include "app.fullname" . }}
        subset: {{ .Values.traffic.canaryLabel }}
      mirrorPercent: 100
      {{ end }}
{{ end }}     
